### ISSUE TITLE
Feedback Fab Lab Project Management

### ISSUE THREAD

**Issue by ivanmilara** [diepnguyenhoang/my_website#1]
# Principles and Practice Feedback #

## From Assessment guide ##

* [x] Sketched your final project idea/s
* [x] Described what it will do and who will use it

### About your website ###
The website contains all required information. It is using default template provided. 

### About your project  ###
You need to provide a little bit more information on your project idea. Explain who might be interested in using and how. Furthermore, the project should include electronics (sensors + actuator + microcontroller). Please, have a second iteration in your project idea in order to meet requirements for the course. 

# Project Management #
## From Assessment guide ##

* [ ] Made a website and described how you did it
* [x] Created a section about yourself on that website
* [x] Added a page with a sketch and description of your final project idea(s)
* [ ] Documented steps for creating your Git repository and adding files to it
* [x] Pushed to the class GitLab

### About your project  website ###
Move your project idea from Principles and Practices to Project.

### About me website ###
It contains basic information. Perhaps you may want to modify your social media at the bottom of the page. It would be nice to provide up-to-date contact information just in case someone would like to contact you. 

### Description of the GIT process ###
* You should clearly differentiate what is GIT and what is Gitlab and Github-> Define what is Github. 
* You say: 
> Then it will generate the 2 keys in my local repo.

Keys are not generated in local repo, but in ssh configuration folder. 
* You are configuring gitlab, but then you are using github. 
   * Please, explain how do you upload the SSH keys to github also. 
   * Please, explain where do you get the clone url for github.
* You should use SSH authentication. HTTPS authentication is not OK.  
*  Please, clarify following git commands in bullet 5: 
  * `git commit`: Stores the commit in your local repo. 
  * `git add `: Append one or more files to the commit that is being created. 
*  Figure 2: .gitignore is OK in github. The file that you do not need in Github is `.gitlab-ci.yml`

### Description of the website ###
* Explain what is a static site generator, and name the one you are using (mkdocs). Explain what is a theme and which theme you have used. 
* Explain what is the `mkdocs.yml`file and how you edited it. 
* Explain what does the command  `mkdocs build` does. 
* Explain what is _markdown_ and how did you use it to edit your files. For instance, how did you add picture? how did you include linkes?

 

### Other comments ###
* What we are requiring is a kind of learning journal, in which you need to include also technical aspects.

**Comment by diepnguyenhoang** [comment]
Hi Ivan,
I have modified my assignment as per feedbacks.
Kindly help to check.
Sincerely,

**Comment by ivanmilara** [comment]
Hi Diep, 

You have clearly improved your work. Just few minor comments: 

* The text in added1.jpg is almost not visible. I recommend you to use png for screenshots. You may want to have also better resoulution
* Explain the git commands. What does `git status`, `git add`, `git commit` and `git push` do?
* You say: "_As such, a static web generator is needed_" You do not really need a static website generator to build a static site. You can build it by hand. Static site generator will simplify the process, allowing, for instance writing markdown vs HTML.  Actually, a static site is such in which the HTML code is fixed and is not generated dynamycally per HTTP Requests. 
* `Mkdocs build` command does not really do what you write there. `mkdocs build` takes your source code in markdown and generated the HTML, CSS and javascript code necessary to build the website based on your theme. This is independent from git, that meets a totally different function. 

Please, let me know when I can check it again.

**Comment by diepnguyenhoang** [comment]
Hi Ivan,
Thank you so much for your feedback, it makes me understand more clearly.
I have editted accordingly.
Kindly help to check again.
Sincerely,

**Comment by ivanmilara** [comment]
Hei, apologies for the delay. It is almost perfect. You just need to clarify a few concepts that are used wrongly. 

* In section 6 you say: 

> _Create a new folder in my computer (local repository) for the website, here I named it as fablabcoursehub_

You do not create a local repository when you create a folder, but when you call `git init` or `git clone`. And actually, the local repository wont be visible by you, you can just see the workspace (the files you are using).  You should rephrase this sentence: _Create a new folder which will contain the workspace and local repository for the website,_

* You also say in same section: 

> Generate SSH Keys in GitHub to authenticate myself with the system:

The SSH key was generated already. You just upload the SSH public key to Github. 

* In MKDOCS section you say: 

> The website I am going to build is a static web which is built with much simple codes/language, allow simple navigation 

The static web does not involve simple language or navigation. It is just different one. The main difference between static and dynamic site is what you mention later: _In a static site, the HTML code is fixed and is not generated dynamically per HTTP Requests_

* Insert a link to mkdocs

* You say: 

> requires Python (or pip),

Python is the programming language and the environment (everything you need to write and execute programs in python). Pip is a package manager for python, that is, a software that allows you to install the software you need to write specific programs. That is Python and PIP are not the same. Pip is part of python. 


* You say: 

> docs => do not touch this folder, this will store data generated from the remote repo. This is my Local repo which stores different version of my projects inside my computer. In contrast, remote repo will store different version of my projects in a remote server.

This sentence is totally messy. You should change it for something like: _docs => this folder contains the website that will be deployed when we commit to github_

Let's see if I can explain why what you have written does not make that much sense:  

In GIT you have: 

  - __Workspace__: The place where you are editing your files. Are the folder in your computer.
  - __Local repository__: A database where you store the changes you do to files in workspace. The files are in your computer.
  - __Remote repository__: A copy of the local repository that is stored in an external computer and that is usually shared with other developers.

Another important point: you can use mkdocs, without using a GIT repository. You can upload the content generated by your mkdocs in any web server (without need to use GIT). So: as you say `_docs` is the folder where you are going to store your source code: the code that you are modifyng. When you compile (you transform from your markdown to HTML) the result (the generated website) will be uploaded to `docs`. Why do you need a folder named `docs`? Because of how Github Web deployment works. When you deploy a web using Github, you need to upload the files in a folder named `docs` (actually there are other options, but this is the one we have chosen in this course). All the files that are in the `docs`folder will be presented in the website. However, `docs` is not your local repo, neither your workspace, and does not store data coming from the remote repo.   

Another note: In mkdocs you can change the names of the folders `docs` and `_docs`. The naming is provided in the configuration file `mkdocs.yml` that you give later. 

* You say: 

> Git add . will add any changes I made above in the working directory to the remote repo. 

`git add .` defines the files that are going to be added to the next commit in the local repo. __Not remote repo__.

* You say: 

> We will finally have linked the file docs from local repo to remote repo.

I do not understand what you mean with this sentence. 

* In the image below the following text _This is how it looks like when I was using markdown to write my assignment on Notepad++_ you should add how this is shown after running the `mkdocs build` command. 

* The link to FastStone Photo resizer is not show.

**Comment by diepnguyenhoang** [comment]
Hi Ivan,
Thank you for your feedback.
I have corrected as per your suggestion, and also make it more understandable. 
Sorry for some places are quite unclear.
Please have a check.
Sincerely,

**Comment by ivanmilara** [comment]
Hi Diep, Great job! Everything is ready now. I will close the issue and inform Jani.
